import { FabricMaterial } from '../types';

export const FABRICS: FabricMaterial[] = [
  {
    id: 'cotton-white',
    name: 'Cotton White',
    color: '#F5F5F0',
    roughness: 0.85,
    metalness: 0.0,
    weight: 'medium',
    description: 'Classic white cotton, versatile and breathable',
    category: 'cotton',
  },
  {
    id: 'cotton-black',
    name: 'Cotton Black',
    color: '#1A1A1A',
    roughness: 0.85,
    metalness: 0.0,
    weight: 'medium',
    description: 'Essential black cotton for everyday wear',
    category: 'cotton',
  },
  {
    id: 'cotton-navy',
    name: 'Navy Cotton',
    color: '#1B3A6B',
    roughness: 0.82,
    metalness: 0.0,
    weight: 'medium',
    description: 'Classic navy cotton, perfect for casual styles',
    category: 'cotton',
  },
  {
    id: 'silk-ivory',
    name: 'Silk Ivory',
    color: '#FFF8E7',
    roughness: 0.2,
    metalness: 0.1,
    weight: 'light',
    description: 'Luxurious ivory silk with a subtle sheen',
    category: 'silk',
  },
  {
    id: 'silk-black',
    name: 'Silk Black',
    color: '#0D0D0D',
    roughness: 0.15,
    metalness: 0.15,
    weight: 'light',
    description: 'Elegant black silk with reflective surface',
    category: 'silk',
  },
  {
    id: 'silk-red',
    name: 'Silk Red',
    color: '#C41E3A',
    roughness: 0.2,
    metalness: 0.1,
    weight: 'light',
    description: 'Vibrant red silk for statement pieces',
    category: 'silk',
  },
  {
    id: 'denim-blue',
    name: 'Classic Denim',
    color: '#4A7AB5',
    roughness: 0.95,
    metalness: 0.0,
    weight: 'heavy',
    description: 'Classic blue denim with textured weave',
    category: 'denim',
  },
  {
    id: 'denim-dark',
    name: 'Dark Denim',
    color: '#2B3A52',
    roughness: 0.95,
    metalness: 0.0,
    weight: 'heavy',
    description: 'Dark wash denim for a refined look',
    category: 'denim',
  },
  {
    id: 'leather-black',
    name: 'Black Leather',
    color: '#1C1C1C',
    roughness: 0.3,
    metalness: 0.05,
    weight: 'heavy',
    description: 'Smooth black leather with subtle gloss',
    category: 'leather',
  },
  {
    id: 'leather-brown',
    name: 'Tan Leather',
    color: '#C4873A',
    roughness: 0.35,
    metalness: 0.05,
    weight: 'heavy',
    description: 'Rich tan leather, natural grain texture',
    category: 'leather',
  },
  {
    id: 'wool-gray',
    name: 'Gray Wool',
    color: '#8A8A8A',
    roughness: 0.95,
    metalness: 0.0,
    weight: 'heavy',
    description: 'Warm gray wool blend for structured pieces',
    category: 'wool',
  },
  {
    id: 'wool-camel',
    name: 'Camel Wool',
    color: '#C19A6B',
    roughness: 0.9,
    metalness: 0.0,
    weight: 'heavy',
    description: 'Luxurious camel tone wool coat material',
    category: 'wool',
  },
  {
    id: 'synthetic-teal',
    name: 'Stretch Teal',
    color: '#008080',
    roughness: 0.6,
    metalness: 0.05,
    weight: 'light',
    description: 'Stretchy synthetic blend, athletic style',
    category: 'synthetic',
  },
  {
    id: 'cotton-coral',
    name: 'Coral Cotton',
    color: '#FF6B6B',
    roughness: 0.82,
    metalness: 0.0,
    weight: 'medium',
    description: 'Vibrant coral cotton for summer styles',
    category: 'cotton',
  },
  {
    id: 'silk-emerald',
    name: 'Emerald Silk',
    color: '#2ECC71',
    roughness: 0.18,
    metalness: 0.12,
    weight: 'light',
    description: 'Rich emerald silk for evening wear',
    category: 'silk',
  },
];

export const FABRIC_CATEGORIES = ['cotton', 'silk', 'denim', 'leather', 'wool', 'synthetic'] as const;
